### ISSUE TITLE
There Might Be An Issue On Using SPI-1 Pins

### ISSUE THREAD

**Issue by MertKalkanci** [AndyRids/pico-nrf24#5]
Hi there, I failed to transmitt data on SPI-1 Pins, I will make some changes and test the driver again on SPI 1 and will reply back to this issue.

I will make an pull request if there isn't anyhingg wrong on my code rather than the driver. Just opened an issue to notify contributors and watchers.

If anyone tested the driver on SPI 1 it would be better to know so it will let me solve my issue faster, thank you.

**Comment by LinoFel** [comment]
Hi there, I can use the SPI1 pins without any problem. Greetings.

**Comment by MertKalkanci** [comment]
Closing the issue because switched to a lora module to use on my project. Also thanks for your comment Lino.
